steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.4.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - 'terraform init'
- id: 'tf apply'
  name: 'hashicorp/terraform:1.4.4'
  entrypoint: 'sh'
  args: 
  - '-c'
  - 'terraform destroy -auto-approve'
  env:
  - 'TF_VAR_project=$PROJECT_ID'
  